name: share
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+21
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.5
  shared_preferences: ^2.0.18
  mocktail: ^0.3.0
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.3
  flutter_svg: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  intl: any
  logger: ^1.3.0
  package_info_plus: ^3.1.2
  auto_size_text: ^3.0.0
  bloc_test: ^9.1.3
  photo_view: ^0.14.0
  open_file: ^3.3.2
  path_provider: ^2.0.15
  share_plus: "^7.0.0"
  signature: ^5.4.0
  http_parser: ^4.0.2
  camera: ^0.10.5+2
  path: ^1.8.3
  image_picker: ^1.0.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/app/android/ic_launcher.png"
  image_path_ios: "assets/icons/app/ios/ic_launcher.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/login/
    - assets/icons/login/
    - assets/icons/fa/solid/
    - assets/icons/app/
    - assets/images/assignments/
    - assets/images/protocol/
    - assets/icons/protocol/
    - assets/icons/assignments/
    - assets/icons/documents/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
flutter_intl:
  enabled: true
